[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.7.3"
nom = "7.1.3"
petgraph = "0.6.4"
priority-queue = "1.3.2"
rand = "0.8.5"
z3 = "0.12.1"
